name: skaletek_kyc
description: "A Flutter SDK for integrating Skaletek's eKYC verification services."
version: 0.0.11
homepage: https://docs.skaletek.io/ekyc/flutter-sdk/

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

  http: ^1.5.0
  image_picker: ^1.2.0
  camera: ^0.11.3
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  flutter_svg: ^2.2.2
  google_fonts: ^6.3.2
  provider: ^6.1.5
  face_liveness_detector: ^0.2.8
  amplify_flutter: ^2.7.0
  amplify_auth_cognito: ^2.7.0
  file_picker: ^10.3.3
  image: ^4.5.4
  web_socket_channel: ^3.0.3
  permission_handler: ^12.0.1
  open_file: ^3.5.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # Bundle AWS configuration files with the plugin
  assets:
    - assets/images/
    - assets/amplifyconfiguration.json
    - assets/awsconfiguration.json
