name: skaletek_kyc
description: "A Flutter SDK for integrating Skaletek's eKYC verification services."
version: 0.0.6
homepage: https://docs.skaletek.io/ekyc/flutter-sdk/

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

  http: ^1.1.0
  image_picker: ^1.0.4
  camera: ^0.11.2
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.7
  google_fonts: ^6.2.1
  provider: ^6.1.1
  face_liveness_detector: ^0.2.7
  amplify_flutter: ^2.0.0
  amplify_auth_cognito: ^2.0.0
  file_picker: ^10.2.0
  image: ^4.5.4
  web_socket_channel: ^2.4.0
  permission_handler: ^11.3.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true

  # Bundle AWS configuration files with the plugin
  assets:
    - assets/images/
    - assets/amplifyconfiguration.json
    - assets/awsconfiguration.json
